-d C:\Users\rffkm\WorkSpace\BF\gowin\DriveStrengthExperiment\impl\gwsynthesis\DriveStrengthExperiment.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\rffkm\WorkSpace\BF\gowin\DriveStrengthExperiment\src\DriveStrength.cst
-cfg C:\Users\rffkm\WorkSpace\BF\gowin\DriveStrengthExperiment\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
